version: '3.5'
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "80:80"
    networks:
      - albert-web_default
      - docs_default

networks:
  albert-web_default:
    external: true
  docs_default:
    external: true
